DEFAULT_ARTIFACT_DIR = ".pclens"
DEFAULT_INDEX_FILE = "index.json"
DEFAULT_GRAPH_FILE = "code_graph.json"
DEFAULT_MEMORY_SUBDIR = "memory"
DEFAULT_TASK_SUBDIR = "tasks"

DEFAULT_MEMORY_DIR = f"{DEFAULT_ARTIFACT_DIR}/{DEFAULT_MEMORY_SUBDIR}"
DEFAULT_TASK_DIR = f"{DEFAULT_ARTIFACT_DIR}/{DEFAULT_TASK_SUBDIR}"
